<?php

namespace Platform\Social;

/**
 * Class Module
 *
 * @package Social
 */
class Module extends \Kendo\Application\Module
{
    public function start()
    {
    }


    public function complete()
    {
        parent::complete(); // TODO: Change the autogenerated stub
    }

}